tuple_film = ('Avengers', 'Joker', 'Suicide Squad', 'Iron Man')
print(tuple_film[0:1])
print(tuple_film[0:2])
print(tuple_film[2:3])
print(tuple_film[0:-1])
print(tuple_film[-1:-3])
print(tuple_film[-1:3])
print(tuple_film[-3:-1])