tuple_game = ('Mobile Legend', 'Apex', 'Arknight', 'PUBG')
print(tuple_game[0:])
print(tuple_game[1:])
print(tuple_game[2:])
print(tuple_game[3:])
print(tuple_game[:0])
print(tuple_game[:1])
print(tuple_game[:2])
print(tuple_game[:3])
print(tuple_game[:4])