tuple_buah = ('Pisang', 'Nanas', 'Melon', 'Durian')
print(tuple_buah[0:])
print(tuple_buah[1:])
print(tuple_buah[2:])
print(tuple_buah[3:])
print(tuple_buah[:0])
print(tuple_buah[:1])
print(tuple_buah[:2])
print(tuple_buah[:3])
print(tuple_buah[:4])